apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vobject
  description: A full-featured Python package for parsing and creating iCalendar and
    vCard files
  annotations:
    business-unit: EverHealth
    github.com/project-slug: drchrono/vobject
    product: DRC
spec:
  type: service
  lifecycle: production
  owner: EverHealth
  implementation:
    languages:
    - Python
